### ISSUE TITLE
Closing connections incorrectly removes all streams

### ISSUE THREAD

**Issue by dermotduffy** [AlexxIT/go2rtc#116]
I have multiple streams being transcoded from rtsp to mjpeg, and multiple fetches of one of the mjpeg streams from a single page/[java]script. Occasionally, when the page is closed, go2rtc will "forget" all stream sources until it is manually restarted. This is equivallent to deleting them all manually using the `delete` link.

This is fairly reproducible for me. Start `go2rtc`, load up the page that consumes the streams, observe multiple mpeg streams in the Chrome devtools network window, close the page, go2rtc stream list becomes empty (see below):

![Screen Shot 2022-11-21 at 3 03 03 PM](https://user-images.githubusercontent.com/1136829/203087885-1011b2b1-4f45-46e0-a28c-355265e34c09.png)

**Comment by AlexxIT** [comment]
Streams added from the web interface are not stored between restarts. This is by design.
https://github.com/AlexxIT/go2rtc#fast-start

**Comment by NickM-27** [comment]
@AlexxIT I think that is not what is being reported. I believe the streams are added via a config file and @dermotduffy is saying there are some cases where the streams list is empty which is fixed via restart

**Comment by dermotduffy** [comment]
Thanks @NickM-27 . Yes, the erased streams are in the config file which I would expect to persist. There is a bug that causes that stream list to entirely empty when the process is under load.

**Comment by AlexxIT** [comment]
Please check if problem persist in `v0.1-rc.4`

**Comment by markfrancisonly** [comment]
> Please check if problem persist in `v0.1-rc.4`

Yes, still

**Comment by felipecrs** [comment]
I can also confirm this. Happens sometimes.

**Comment by AlexxIT** [comment]
Closed by mistake

**Comment by AlexxIT** [comment]
Should be fixed on latests versions

**Comment by markfrancisonly** [comment]
still persists in go2rtc 0.1-rc.9, opening connection to 16 cameras on my ipad reliably crashes go2rtc

Also tried removing ffmpeg audio transcoding in attempt to resolve a separate issue with audio out of sync with video in frigate recordings, crashes with or without ffmpeg transcoding

**Comment by AlexxIT** [comment]
You need to provide crash error

**Comment by markfrancisonly** [comment]
yes okay but this issue is not closed my friend, the problem is still present in v1.1.0.

when I've enabled tracing for my 16 camera views, but the server bogged down too much. need more time to find the suitable log level. unfortunately I'm now experiencing total freezing in video streams, which wasn't previously a problem in earlier builds.

in the interim, I'm going to put the go2rtc container on a 5 minute restart cron job...

**Comment by markfrancisonly** [comment]
still in 1.20 .... should be easy to fix, but the bug destabilizes go2rtc.  The following bash script restarts the go2rtc container from the outside. if you can't track down the cause, perhaps implement the same inside the container ....

```
#!/bin/bash

url="http://<go2rtc_server>/api/streams"
stream="<stream_name>"
container="<go2rtc_container_name>"

if curl -m 10 -s "$url" | grep -q "$stream"
then
        echo "$stream is available"
else
        echo "$stream is not available, restarting $container"
        docker restart "$container" > null
fi

```

will attempt to log the error error
