### ISSUE TITLE
issue watching cameras streams

### ISSUE THREAD

**Issue by avico78** [AlexxIT/go2rtc#138]
Not able to watch camera on HA (either webapp,chrome) - it usually very unstable and slow.
When open chrome browser directly
http://192.168.1.113:1984/stream.html?src=front_go2rtc
looks good 
On DMSS app - also no issue

So i'm not sure what i'm doing wrong here ,

setup:
3 Dahau 4mp camera - all set to 1080p + AAC
1 VTO 2mp - set to 720P 
go2rtc + HA running on docker on server A
Frigate - docker running on server B

Dahua camera config:

![image](https://user-images.githubusercontent.com/9049952/208897164-04cf1629-c1cf-44dd-8275-7d0ccb2b9b90.png)
![image](https://user-images.githubusercontent.com/9049952/208897209-7f3d24e5-9e07-419c-92c0-e70eb7bb4bef.png)

go2rtc config
```
streams:
  front_go2rtc: rtsp://hauser:xxxxx@192.168.1.110:554/cam/realmonitor?channel=1&subtype=0  
```
trying to watch HA on chrome - not possible , black screen with webrtc:true   :
```
2022-12-21 13:41:27.777 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/12/21 13:41:27 Stream Exit On Demand No Viewer
2022-12-21 13:41:34.230 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/12/21 13:41:34 Set ICEServers [stun:stun.l.google.com:19302]
2022-12-21 13:41:34.244 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/12/21 13:41:34 WebRTC Ignore Audio Track codec not supported WebRTC support only PCM_ALAW or PCM_MULAW
```
without webrtc:true -> very slow video stream and icon of disconnection appears many times.

camera info:
```
[
  {
    "media:0": "video, sendonly, 96 H264/90000",
    "media:1": "audio, sendonly, 97 MPEG4-GENERIC/16000",
    "receive": 1823779176,
    "remote_addr": "192.168.1.55:554",
    "send": 0,
    "track:0": "97 MPEG4-GENERIC/16000, sinks=2",
    "type": "RTSP client producer",
    "url": "rtsp://192.168.1.55:554/cam/realmonitor?channel=1\u0026subtype=0/",
    "user_agent": "go2rtc/0.1-rc.5"
  },
  {
    "media:0": "video, recvonly, 96 H264/90000",
    "media:1": "audio, recvonly, 97 MPEG4-GENERIC/16000",
    "receive": 0,
    "remote_addr": "192.168.1.3:45786",
    "send": 1823718280,
    "track:0": "97 MPEG4-GENERIC/16000, sinks=2",
    "type": "RTSP server consumer",
    "url": "rtsp://192.168.1.113:8554/front_go2rtc",
    "user_agent": "Lavf59.27.100"
  },
  {
    "media:0": "video, recvonly, 96 H264/90000",
    "media:1": "audio, recvonly, 97 MPEG4-GENERIC/16000",
    "receive": 0,
    "remote_addr": "172.29.0.5:41950",
    "send": 1389096584,
    "track:0": "97 MPEG4-GENERIC/16000, sinks=2",
    "type": "RTSP server consumer",
    "url": "rtsp://192.168.1.113:8554/front_go2rtc",
    "user_agent": "Lavf59.16.100"
  }
]
````

**Comment by AlexxIT** [comment]
`custom:webrtc-camera` not related with go2rtc. Check go2rtc default WebUI viewer.

**Comment by AlexxIT** [comment]
Looks like you using Firefox. It has problems in latest release version. But it fixed in latest master version.
Some old devices, usual Android Tablets, can't play video with high bitrate.
Also Firefox has very basic WebRTC support...

**Comment by avico78** [comment]
Thanks Alex , 
what would be ur recommendation for bitrate and bitrate type?

**Comment by avico78** [comment]
really lost here ,it doesn't make sense it's work so slow .
i think i've read every letter in documentation but still can't view cameras properly on the HA ,
I guess i miss something fundamental in the setup so kindly be patient and let me know what i'm missing here,
setup:
go2rtc + HA running on dockers on server A
Frigate - docker running on server B

Frigate :
all cameras using go2rtc

HA:
Install intergration "webrtc camera"
All camera define as generic with using go2rtc streams.
Cards using custom:webrtc 

Result : 
very (!) poor ,hard to believe this is capabilities  of webrtc - 
Do i need to configure something else? install some other package?

I ran some test:
I install RTSPtoWebRTC and configure the url to the go2rtc server,
I create 2 cards , once picture-glance and the other webrtc - 
on webrtc the disoccencted icon appear almost all the time and video is not smoth,
on picture-glance - looks great ,
i must missing something here ...

**Comment by NickM-27** [comment]
webrtc camera has nothing to do with go2rtc and I don't think it even uses the webrtc function of go2rtc in any way (currently). So using webrtc card is not using go2rtc at all. 

The best way to see how things are working from go2rtc side is to simply view the go2rtc webui and play webrtc there.

also, what browser are you using? as it was said previously, firefox has very poor support for webrtc. I use chrome and it has been working flawlessly.

**Comment by avico78** [comment]
> webrtc camera has nothing to do with go2rtc and I don't think it even uses the webrtc function of go2rtc in any way (currently). So using webrtc card is not using go2rtc at all.
> 
> The best way to see how things are working from go2rtc side is to simply view the go2rtc webui and play webrtc there.
> 
> also, what browser are you using? as it was said previously, firefox has very poor support for webrtc. I use chrome and it has been working flawlessly in frigate & in HA.

I'm using chrome , i tried Firefox as thought might work better there ,
obviously my real need is to be able to view the camera on HA app on my mobile .
yes, when i open webui - it looks perfect ,
but not in Home assistant on chrome or the webapp - actually really bad that in case of need I'm using dmss .

**Comment by NickM-27** [comment]
right, if you're using the webrtc card then it is not using go2rtc. I personally use `rtsp2webrtc` integration pointing at `go2rtc_ip:1984` and then https://github.com/dermotduffy/frigate-hass-card for the HA frontend which uses the `HA` stream type. It works perfectly on my iPhone & Android

**Comment by AlexxIT** [comment]
Compare go2rtc Web UI on PC and go2rtc Web UI on your phone. In same home local network.

**Comment by avico78** [comment]
> right, if you're using the webrtc card then it is not using go2rtc. I personally use `rtsp2webrtc` integration pointing at `go2rtc_ip:1984` and then https://github.com/dermotduffy/frigate-hass-card for the HA frontend which uses the `HA` stream type. It works perfectly on my iPhone & Android

did u config the cameras in HA or in go2rtc?
as I need frigate , I define all  camers in go2rtc and use go2rtc in both ha/frigate,
well the thing that confusing, while all camera stream define in ha coming from go2rtc as I did,
why I need to use rtsp2webrtc and connect it to go2rtc? the steam already coming from go2rtc no?

**Comment by NickM-27** [comment]
I'm using the dev version of the frigate integration which exposes the RTSP from go2rtc. You have to point rtsp2webrtc at go2rtc so HA has access to webRTC otherwise it is unaware of the webRTC provider.

**Comment by avico78** [comment]
> Compare go2rtc Web UI on PC and go2rtc Web UI on your phone. In same home local network.
 
both provide smooth stream , externally - not .
I follow ur insurctions for open udp port 50000-50100
and it doesn't help.

please note , all camera configured go2rtc
all consumer using them .
the problem looks I can't view them externally,
I'm not sure if I still need wertc camera intergation 
( currently Its there and define for udp 50000-50100).
for rtsp2webrtc - I read every piece in the documeation, unfortunately it is  orineted to supervisor/hassio and somehow (for me at least) not clearing my doubt in example - 
I'm using go2rtc streams ,why I need to send the back via rtsp2webrtc to go2rtc again ?
second ,go2rtc as understand is the better approach the webrtc camera, why still need to define the udp port there (in case using external ip address),

again ,very sorry I bother u guys with questions , I'm trying the stabilize the situation and actually get more confused as I do follow the documentation and even carefully but for me at least it is confusing .

**Comment by avico78** [comment]
maybe worth mention for network -
I'm using Traefik as reverse proxy and I'm using Traefik labels for handling docker I need to publish to my domain .and also for auto ssl renewal

**Comment by bm55** [comment]
> I'm using the dev version of the frigate integration which exposes the RTSP from go2rtc. You have to point rtsp2webrtc at go2rtc so HA has access to webRTC otherwise it is unaware of the webRTC provider.

@NickM-27 I am using the V4.0.0-beta1 does that not have the RTSP option from go2rtc. 
When I use following setup, it looks like uses WebRTC and work great but it also increased the cpu on my host specially when I launch multiple devices. 

using rtsp://frigate_IP:8554/camera_name on vlc doesn't seem to require additional cpu though so I was hoping to add rtsp feed on HA

```
type: custom:frigate-card
cameras:
  - live_provider: ha
    webrtc_card: {}
    camera_entity: camera.garage
menu:
  position: bottom
```

**Comment by NickM-27** [comment]
@bm55 yes, if you have restream enabled then the camera entities in HA integration will automatically use the RTSP feed as its source.

**Comment by AlexxIT** [comment]
WebRTC Camera v3 now supported go2rtc as streaming server
https://github.com/AlexxIT/WebRTC/releases

**Comment by avico78** [comment]
@AlexxIT  - could u add some explanation for the streaming capabilities and how does it simplify/improve prior approach ?
Thanks

**Comment by AlexxIT** [comment]
It uses new code base for convert RTSP stream format to WebRTC/MSE format.  In any case, the old code base will no longer be supported.
