### ISSUE TITLE
Can go2rtc Configuration Be Stored in a Database Instead of go2rtc.yaml?

### ISSUE THREAD

**Issue by techsupportsardonyx** [AlexxIT/go2rtc#1653]
I am trying to integrate go2rtc with a database where stream configurations (such as stream_name, stream_url) are stored and managed dynamically. Currently, go2rtc requires the configuration to be manually stored in the go2rtc.yaml file, but I would like to store this configuration in a database and dynamically add or remove streams.

**Is there a way to:**

1. Store go2rtc configuration data (like stream settings) in a database (e.g., SQLite, MySQL)?
2. Dynamically generate or update the go2rtc.yaml file from the database, based on added or removed streams?
3. Automate this process, so changes to the database are reflected in the go2rtc.yaml file without manual edits?

**Comment by vegalou** [comment]
Seems same requirement just issued one day ago for playback & easy configuration.

As I know, it's a realized feature somewhere. 😁 `runOnDemand + RegEx`

https://github.com/AlexxIT/go2rtc/issues/1650

@techsupportsardonyx

**Comment by AlexxIT** [comment]
Check available API https://github.com/AlexxIT/go2rtc/tree/master/api

**Comment by copbr** [comment]
The GO2RTC API does work for this, but I have identified a problem.
When I send multiple add requests for new streams (I tried with 24), the API corrupts the configuration file.
I believe this is a BUG.

**Comment by AlexxIT** [comment]
Yes. This can be a bug. You can create another issue with examples of your config before "bad" API call.
Also check go2rtc version, v1.9.9 has a fix about this problem.

**Comment by techsupportsardonyx** [comment]
```
streams:
  test:
    - rtsp://admin:Admin123@172.25.3.30/cam/realmonitor?channel=1&subtype=0
  test1:
    - rtsp://admin:Admin123@172.25.3.30/cam/realmonitor?channel=1&subtype=0
  test2:
    - rtsp://admin:admin123@172.25.10.34/cam/realmonitor?channel=1&subtype=0
```

The RTSP URL for go2rtc is currently stored in the go2rtc.yaml file, but I would like to store this configuration in a database instead (e.g., SQLite or MySQL).

**Comment by techsupportsardonyx** [comment]
Alex ?

**Comment by AlexxIT** [comment]
This functionality is not planned to be integrated into the project. You can develop everything you need yourself.

**Comment by copbr** [comment]
Sorry, Alex. I didn’t mean to be rude or to criticize the API in any way. Go2rtc is amazing and helps me a lot in my daily work. I just wanted to share something I experienced. Even if it turns out to be a bug, it’s nothing urgent — there are several ways to work around it, like adding a 1-second delay between configuration file updates.

**Comment by vegalou** [comment]
@copbr 

I through same solution like your, control configuration by front, 
go2rtc support config update and cron a task clean up expired sessions.

Let's stay on GO2RTC streaming road. 😄

Many thanks to Alex's efforts & help. @AlexxIT

**Comment by AlexxIT** [comment]
Corrupt file is known problem. I just needs an example config file content before API call and example of API call.

**Comment by AlexxIT** [comment]
I thinks corrupt file is fixed in the latest release.

**Comment by bearislove** [comment]
> I thinks corrupt file is fixed in the latest release.

I'm using version 1.9.9 ( current lastest version) but corrupt file still happen sometime when i call API of adding stream
```
/config # go2rtc --version
go2rtc version 1.9.9 (fa580c5) linux/amd64
```
My initial go2rtc.yaml config look like this:

```
api:
  origin: "*"
streams:
```

**Comment by AlexxIT** [comment]
Can you give some specific examples?

**Comment by bearislove** [comment]
> Can you give some specific examples?

It happen sometime, and I'm not sure what the causes. So I describe my flow.

My request add stream simple like this

`curl -X PUT "http://localhost:1984/api/streams?src=rtsp://xxxx&name=camera1"`

Then i  requested many time in a day (same name, src) 

Then i open go2rtc.yaml, the content look like this (This normal content)
```
streams:
  1_CAM_01:
    - rtsp://XXX/snl/live/1/1
  3_CAM_01:
    - rtsp://XXX/snl/live/1/1
  2_CAM_01:
    - rtsp://XXX/snl/live/1/1
```
But sometime the content look like this. (This is error sample content)

```
streams:
  1_CAM_01:
    - rtsp://XXX/snl/live/1/1
  1
  3_CAM_01:
    - rtsp://XXX/snl/live/1/1
```

Error logs

```
02:07:20.905 ERR github.com/AlexxIT/go2rtc/internal/api/ws/ws.go:105 > host=192.168.100.69:1984 origin=http://localhost error="websocket: request origin not allowed by Upgrader.CheckOrigin"
02:07:21.831 ERR github.com/AlexxIT/go2rtc/internal/api/ws/ws.go:105 > host=192.168.100.69:1984 origin=http://localhost error="websocket: request origin not allowed by Upgrader.CheckOrigin"
02:07:22.313 ERR github.com/AlexxIT/go2rtc/internal/api/ws/ws.go:105 > host=192.168.100.69:1984 origin=http://localhost error="websocket: request origin not allowed by Upgrader.CheckOrigin"
02:11:10.105 INF go2rtc platform=linux/amd64 revision=fa580c5 version=1.9.9
02:11:10.105 INF config path=/config/go2rtc.yaml
02:11:10.105 INF [rtsp] listen addr=:8554
02:11:10.106 INF [api] listen addr=:1984
02:11:10.106 INF [webrtc] listen addr=:8555
09:29:18.326 INF [streams] can't get track error="wrong response on SETUP"
09:29:19.130 INF [streams] can't get track error=EOF
06:45:44.300 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:170 > error="read tcp 172.18.0.2:49004->115.75.161.38:12554: i/o timeout" url=rtsp://rtsp:1111111@115.75.161.38:12554/snl/live/1/1
06:49:06.482 INF [streams] can't get track error="wrong response on SETUP"
06:49:06.561 INF [streams] can't get track error=EOF
exit with signal: terminated
01:32:37.464 INF go2rtc platform=linux/amd64 revision=fa580c5 version=1.9.9
01:32:37.464 INF config path=/config/go2rtc.yaml
01:32:37.464 WRN error="yaml: line 3: did not find expected key"
01:32:37.464 WRN error="yaml: line 3: did not find expected key"
01:32:37.464 WRN error="yaml: line 3: did not find expected key"
01:32:37.464 WRN error="yaml: line 3: did not find expected key"
01:32:37.465 INF [rtsp] listen addr=:8554
01:32:37.465 INF [api] listen addr=:1984
01:32:37.465 WRN error="yaml: line 3: did not find expected key"
01:32:37.465 INF [webrtc] listen addr=:8555
```

**Comment by AlexxIT** [comment]
This can happen when you call the API twice at the same time. This can be fixed.
