### ISSUE TITLE
Fix login to Xiaomi account with captcha

### ISSUE THREAD

**Issue by dest16** [AlexxIT/go2rtc#1985]
Unable to log in to my Xiaomi account; after entering my username and password, I'm stuck in an infinite loop of entering a verification code.

<img width="461" height="169" alt="Image" src="https://github.com/user-attachments/assets/18603c48-5e99-4bed-8eb7-09bc7ddedd97" />

**Comment by ptbsare** [comment]
I can verify that this issue exists; it's the same on my end.

**Comment by AlexxIT** [comment]
My tests didn't have captcha, so I wrote the code blind.
You can contact me via Telegram and send me your login/password.

This code works in my other python component. You can use it to get a token:
https://github.com/AlexxIT/XiaomiGateway3

After logging into your Xiaomi account, you can find the token here: `/config/.storage/core.config_entries`
line: `"token":"1234567890:V1:***"`

and add to `go2rtc.yaml` (add space after userID):
```yaml
xiaomi:
  1234567890: V1:***
```

PS. But of course it would be better to fix the authorization in this project.

**Comment by Liujinliang0803** [comment]
> I can verify that this issue exists; it's the same on my end.

me too

**Comment by jchenny7** [comment]
try switch the country to Singapore instead of China.

**Comment by dest16** [comment]
> My tests didn't have captcha, so I wrote the code blind. You can contact me via Telegram and send me your login/password.
> 
> This code works in my other python component. You can use it to get a token: https://github.com/AlexxIT/XiaomiGateway3
> 
> After logging into your Xiaomi account, you can find the token here: `/config/.storage/core.config_entries` line: `"token":"1234567890:V1:***"`
> 
> and add to `go2rtc.yaml` (add space after userID):
> 
> xiaomi:
>   1234567890: V1:***
> PS. But of course it would be better to fix the authorization in this project.

After pasting the ID and token obtained from xiaomigateway3 into the go2rtc config file, saving and restarting, I can see the Xiaomi account with the corresponding ID. However, clicking "load devices" results in a 401 error.

**Comment by AlexxIT** [comment]
You don't need to select a server to log in! The server is used only to retrieve the list of devices.

**Comment by AlexxIT** [comment]
@dest16 Perhaps you copied something incorrectly. I'm sure the tokens are fully compatible. But the format is slightly different (separated by space).

**Comment by dest16** [comment]
> [@dest16](https://github.com/dest16) Perhaps you copied something incorrectly. I'm sure the tokens are fully compatible. But the format is slightly different (separated by space).也许你抄错了什么。我相信这些代币是完全兼容的。但格式稍有不同（被空格分隔）。

My bad, I didn't notice the newline character in the token. This method works.

**Comment by vector-co-uz** [comment]
```
streams:
  camera_outdoor:
    - rtsp://************@10.10.10.200:554/Streaming/Channels/101
  outdoor_preview:
    - rtsp://*********@10.10.10.200:554/Streaming/Channels/102
  xiaomi_c200:
    - xiaomi://4258882842:ru@10.10.10.182?did=1148772601&model=chuangmi.camera.046c04
```
Then the token. If I open the camera stream, I get an error. Where is my mistake?

`mse: streams: miss: read auth: {"result":"failed","code":3}`

**Comment by gujiangjiang** [comment]
it's the same with me

**Comment by AlexxIT** [comment]
It won't be fixed until I have an account where I can replicate the issue.

**Comment by vanscer** [comment]
it works

**Comment by wang923345843** [comment]
> > [@dest16](https://github.com/dest16)也许你复制了一些不正确的东西。我确信这些令牌是完全兼容的。但格式略有不同（用空格分隔）。也许你抄错了什么。我相信这些代币是完全兼容的。但格式稍有不同（被空格分隔）。
> 
> 我的错，我没注意到标记中的换行符。这个方法有效。

xiaomi:
  小米智能摄像机C700: V1:34754c485358326a4d62334750553aaa

streams:
  xiaomi1: 	xiaomi://小米智能摄像机C700:cn@192.168.124.30?did=1190604173（问一下，这里是代表什么，我填的是摄像头id，用milco测出来的）&model=chuangmi.camera.081ae2              但是使用rtsp://192.168.124.30:8554/xiaomi1无法播放

**Comment by sumsethan** [comment]
where you put
> 小米智能摄像机C700

should be your uid

btw,you are right about the  did part

**Comment by wang923345843** [comment]
> 你填成
> 
> > 小米智能枢纽C700
> 
> 的地方，应该是你的uid
> 
> did 理解的正确

xiaomi:
  17516381234: V1:34754c485358326a4d6233475055aaa

streams:
  xiaomi1: 	xiaomi://17516381234:cn@192.168.124.50?did=1190604173&model=chuangmi.camera.81ac1

uid是我小米登录的手机号，V1:后面是homeassistant的xiaomigateway3 读出来的token，192.168.124.50是摄像头的ip（请问这里写摄像头ip还是docker的ip，docker的ip是192.168.124.23）， 最后rtsp://192.168.124.50:8554/xiaomi1读不出来，还请指教

**Comment by AlexxIT** [comment]
Communication in this repository is in English only.

**Comment by sumsethan** [comment]
> Communication in this repository is in English only.

OK ,edited

hope this issue can be solve asap,you may use my username/password if needed

**Comment by sumsethan** [comment]
> > 你填成
> > > 小米智能枢纽C700
> > 
> > 
> > 的地方，应该是你的uid
> > did 理解的正确
> 
> xiaomi: 17516381234: V1:34754c485358326a4d6233475055aaa
> 
> streams: xiaomi1: xiaomi://17516381234:cn@192.168.124.50?did=1190604173&model=chuangmi.camera.81ac1
> 
> uid是我小米登录的手机号，V1:后面是homeassistant的xiaomigateway3 读出来的token，192.168.124.50是摄像头的ip（请问这里写摄像头ip还是docker的ip，docker的ip是192.168.124.23）， 最后rtsp://192.168.124.50:8554/xiaomi1读不出来，还请指教

read this thread carefully

**Comment by wang923345843** [comment]
> > > 你填成
> > > > 小米智能枢纽C700
> > > 
> > > 
> > > 的地方，应该是你的uid
> > > did 理解的正确
> > 
> > 
> > xiaomi: 17516381234: V1:34754c485358326a4d6233475055aaa
> > streams: xiaomi1: xiaomi://17516381234:cn@192.168.124.50?did=1190604173&model=chuangmi.camera.81ac1
> > uid是我小米登录的手机号，V1:后面是homeassistant的xiaomigateway3 读出来的token，192.168.124.50是摄像头的ip（请问这里写摄像头ip还是docker的ip，docker的ip是192.168.124.23）， 最后rtsp://192.168.124.50:8554/xiaomi1读不出来，还请指教
> 
> read this thread carefully

谢谢，已经搞好了，这个uid需要从那个文件里面找，现在转码也成功了，谢谢

**Comment by AlexxIT** [comment]
Fixed in latest master version. Will be in next release.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/releases/tag/v1.9.14

**Comment by Ljzd-PRO** [comment]
v1.9.14 can send SMS codes and log in, but it still cannot obtain the passToken. It seems that go2rtc retrieves the passToken from Cookies, but packet capture reveals that none of the request responses contain the passToken. The reason for this is unclear. Using other passToken retrieval tools, the passToken can be successfully obtained to list devices.

**Comment by iamyaofeng** [comment]
> v1.9.14 can send SMS codes and log in, but it still cannot obtain the passToken. It seems that go2rtc retrieves the passToken from Cookies, but packet capture reveals that none of the request responses contain the passToken. The reason for this is unclear. Using other passToken retrieval tools, the passToken can be successfully obtained to list devices.

me too,please tell me what other passToken retrieval tools you used?thanks!

**Comment by Ljzd-PRO** [comment]
> > v1.9.14 can send SMS codes and log in, but it still cannot obtain the passToken. It seems that go2rtc retrieves the passToken from Cookies, but packet capture reveals that none of the request responses contain the passToken. The reason for this is unclear. Using other passToken retrieval tools, the passToken can be successfully obtained to list devices.
> 
> me too,please tell me what other passToken retrieval tools you used?thanks!

https://github.com/leriocn/MI-PassToken-Helper

**Comment by AlexxIT** [comment]
I can't fix a problem if I can't repeat it. If you want this issue fixed, either fix it yourself and create a PR, or send me your account details via PM.

**Comment by jmaris** [comment]
I'm pretty sure this is a problem on Xiaomi's side. I get this issue in their official GUI on my device trying to log in.
