### ISSUE TITLE
RTC feed freezes after few minutes since updating to 1.8.5

### ISSUE THREAD

**Issue by oleg-d** [AlexxIT/go2rtc#928]
With 1.8.4 it didn't happen, I have the feed running on my HA dashboard for 16 hours a day every day. Updating to 1.8.5 and the camera feed freezes after some minutes, not sure exactly how many minutes, maybe like 10-15 minutes the feed will freeze.

Reverting back to 1.8.4 fixes the problem for me. My tablet is Fire HD 10 (2021), running Fully Kiosk app.

**Comment by AlexxIT** [comment]
You need to provide more info about your setup. More than 40 files changed since v1.8.4

**Comment by oleg-d** [comment]
What kind of information do you think would help in trying to debug?

I have the camera coming in from the [tuya smartlife](https://github.com/tuya/tuya-smart-life) integration.

My `go2rtc.yaml`  file looks like this:
```
api:
  listen: 127.0.0.1:1984
  password: '123'
  username: admin
rtsp:
  password: '123'
  username: admin
streams:
  my_camera:
    - echo:bash /config/custom_components/expose_camera_stream_source/get_stream.sh camera.camera

```
I then have the camera in a card like this:
```
  - type: custom:webrtc-camera
    url: rtsp://admin:123@192.168.50.222:8554/my_camera?mp4
```

go2rtc add-on log:
```
21:32:08.071 INF go2rtc version 1.8.5 linux/amd64
21:32:08.073 INF [rtsp] listen addr=:8554
21:32:08.076 INF [api] listen addr=127.0.0.1:1984
21:32:08.080 INF [webrtc] listen addr=:8555
21:32:08.083 INF [hass] listen addr=172.30.32.1:1984
21:42:14.343 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error=EOF url="echo:bash /config/custom_components/expose_camera_stream_source/get_stream.sh camera.camera"
21:53:04.299 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error=EOF url="echo:bash /config/custom_components/expose_camera_stream_source/get_stream.sh camera.camera"
22:03:05.835 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error=EOF url="echo:bash /config/custom_components/expose_camera_stream_source/get_stream.sh camera.camera"
```

These warnings were also present in 1.8.4 too but maybe something in 1.8.5 doesn't like these and is causing a freeze.

**Comment by AlexxIT** [comment]
Tuya already talking a lot. Check the other issues. This is a duplicate. And it looks like this is not go2rtc problem

**Comment by oleg-d** [comment]
I don't see another issue related to feed freezing. If it was tuya then why would 1.8.4 work.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/issues/908

Are you really sure that v1.8.4 doesn't has this problem?

**Comment by oleg-d** [comment]
Positive 100% on 1.8.4 my feed does not freeze, I have it running all day on the dashboard.
And the logs produce the same EOF warning.
```
22:15:30.865 INF go2rtc version 1.8.4 linux/amd64
22:15:30.865 INF [rtsp] listen addr=:8554
22:15:30.866 INF [api] listen addr=127.0.0.1:1984
22:15:30.866 INF [webrtc] listen addr=:8555
22:15:30.870 INF [hass] listen addr=172.30.32.1:1984
22:26:37.788 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error=EOF url="echo:bash /config/custom_components/expose_camera_stream_source/get_stream.sh camera.camera"
22:36:39.459 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error=EOF url="echo:bash /config/custom_components/expose_camera_stream_source/get_stream.sh camera.camera"
22:46:40.939 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error=EOF url="echo:bash /config/custom_components/expose_camera_stream_source/get_stream.sh camera.camera"
22:56:42.445 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error=EOF url="echo:bash /config/custom_components/expose_camera_stream_source/get_stream.sh camera.camera"
23:06:43.953 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error=EOF url="echo:bash /config/custom_components/expose_camera_stream_source/get_stream.sh camera.camera"
```

**Comment by AlexxIT** [comment]
Reconnection issue should be fixed in latest master version

**Comment by EricCorleone** [comment]
I've tried the master version, and the feed still freezes every ten minutes (Tuya Pet Feeder), so I have to use automation to restart go2rtc addon every ten minutes lol
